// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mjbtxhqzseperfhzexxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qYnR4aHF6c2VwZXJmaHpleHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODYxODYsImV4cCI6MjA2OTk2MjE4Nn0.JbA8Qkl6UT0FGvApggwzDdc_tGE-cfM-nuX9DM-Fexw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);